package com.digitalsolutionarchitecture.bpmnlayoutanalyzer.analyze;

public enum EdgeDirection {
	
	DIRECT_LEFT_RIGHT,
	DIRECT_LEFT_UPPERRIGHT,
	DIRECT_BOTTOM_TOP,
	DIRECT_RIGHT_UPPERLEFT,
	DIRECT_RIGHT_LEFT,
	DIRECT_RIGHT_LOWERLEFT,
	DIRECT_TOP_BOTTOM,
	DIRECT_LEFT_LOWERRIGHT,
	
	PERPENDICULAR_LEFT_RIGHT,
	PERPENDICULAR_LEFT_UPPERRIGHT,
	PERPENDICULAR_BOTTOM_TOP,
	PERPENDICULAR_RIGHT_UPPERLEFT,
	PERPENDICULAR_RIGHT_LEFT,
	PERPENDICULAR_RIGHT_LOWERLEFT,
	PERPENDICULAR_TOP_BOTTOM,
	PERPENDICULAR_LEFT_LOWERRIGHT,
	
	ZAGGED_LEFT_RIGHT,
	ZAGGED_LEFT_UPPERRIGHT,
	ZAGGED_BOTTOM_TOP,
	ZAGGED_RIGHT_UPPERLEFT,
	ZAGGED_RIGHT_LEFT,
	ZAGGED_RIGHT_LOWERLEFT,
	ZAGGED_TOP_BOTTOM,
	ZAGGED_LEFT_LOWERRIGHT,
	
	BEND_LEFT_RIGHT,
	BEND_LEFT_UPPERRIGHT,
	BEND_BOTTOM_TOP,
	BEND_RIGHT_UPPERLEFT,
	BEND_RIGHT_LEFT,
	BEND_RIGHT_LOWERLEFT,
	BEND_TOP_BOTTOM,
	BEND_LEFT_LOWERRIGHT;
	
	public static final EdgeDirection[] LEFT_RIGHT_FACING_ARCS = new EdgeDirection[] { 
		EdgeDirection.BEND_LEFT_LOWERRIGHT, 
		EdgeDirection.BEND_LEFT_RIGHT, 
		EdgeDirection.BEND_LEFT_UPPERRIGHT, 
		EdgeDirection.DIRECT_LEFT_LOWERRIGHT,
		EdgeDirection.DIRECT_LEFT_RIGHT,
		EdgeDirection.DIRECT_LEFT_UPPERRIGHT,
		EdgeDirection.PERPENDICULAR_LEFT_LOWERRIGHT,
		EdgeDirection.PERPENDICULAR_LEFT_UPPERRIGHT,
		EdgeDirection.PERPENDICULAR_LEFT_RIGHT,
		EdgeDirection.ZAGGED_LEFT_LOWERRIGHT,
		EdgeDirection.ZAGGED_LEFT_UPPERRIGHT,
		EdgeDirection.ZAGGED_LEFT_RIGHT
	};
	
	public static final EdgeDirection[] RIGHT_LEFT_FACING_ARCS = new EdgeDirection[] {
		EdgeDirection.BEND_RIGHT_LEFT,
		EdgeDirection.BEND_RIGHT_LOWERLEFT,
		EdgeDirection.BEND_RIGHT_UPPERLEFT,
		EdgeDirection.DIRECT_RIGHT_LEFT,
		EdgeDirection.DIRECT_RIGHT_LOWERLEFT,
		EdgeDirection.DIRECT_RIGHT_UPPERLEFT,
		EdgeDirection.PERPENDICULAR_RIGHT_LEFT,
		EdgeDirection.PERPENDICULAR_RIGHT_LOWERLEFT,
		EdgeDirection.PERPENDICULAR_RIGHT_UPPERLEFT,
		EdgeDirection.ZAGGED_RIGHT_LEFT,
		EdgeDirection.ZAGGED_RIGHT_LOWERLEFT,
		EdgeDirection.ZAGGED_RIGHT_UPPERLEFT
	};
	
	public static final EdgeDirection[] TOP_BOTTOM_FACING_ARCS = new EdgeDirection[] {
		EdgeDirection.BEND_LEFT_LOWERRIGHT,
		EdgeDirection.BEND_RIGHT_LOWERLEFT,
		EdgeDirection.BEND_TOP_BOTTOM,
		EdgeDirection.DIRECT_LEFT_LOWERRIGHT,
		EdgeDirection.DIRECT_RIGHT_LOWERLEFT,
		EdgeDirection.DIRECT_TOP_BOTTOM,
		EdgeDirection.PERPENDICULAR_LEFT_LOWERRIGHT,
		EdgeDirection.PERPENDICULAR_RIGHT_LOWERLEFT,
		EdgeDirection.PERPENDICULAR_TOP_BOTTOM,
		EdgeDirection.ZAGGED_LEFT_LOWERRIGHT,
		EdgeDirection.ZAGGED_RIGHT_LOWERLEFT,
		EdgeDirection.ZAGGED_TOP_BOTTOM
	};

	public static final EdgeDirection[] BOTTOM_TOP_FACING_ARCS = new EdgeDirection[] {
		EdgeDirection.BEND_LEFT_UPPERRIGHT,
		EdgeDirection.BEND_RIGHT_UPPERLEFT,
		EdgeDirection.BEND_BOTTOM_TOP,
		EdgeDirection.DIRECT_LEFT_UPPERRIGHT,
		EdgeDirection.DIRECT_RIGHT_UPPERLEFT,
		EdgeDirection.DIRECT_BOTTOM_TOP,
		EdgeDirection.PERPENDICULAR_LEFT_UPPERRIGHT,
		EdgeDirection.PERPENDICULAR_RIGHT_UPPERLEFT,
		EdgeDirection.PERPENDICULAR_BOTTOM_TOP,
		EdgeDirection.ZAGGED_LEFT_UPPERRIGHT,
		EdgeDirection.ZAGGED_RIGHT_UPPERLEFT,
		EdgeDirection.ZAGGED_BOTTOM_TOP
	};
}
